language: java

jdk:
  - oraclejdk8

script:
  - mvn -B clean install jacoco:report
  - mvn -f examples/pom.xml clean test

addons:
   hosts:
       - travis
   hostname: travis

before_script:
  - pip install --user codecov
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import

after_success:
  - codecov
  - mvn sonar:sonar -Dsonar.projectKey=SwayDB.java -Dsonar.organization=simerplaha-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
